services:
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - frontend
      - backend

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=${PORT:-8000}
      - API_SECRET=${API_SECRET}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=${DATABASE_NAME}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8001:80"
    networks:
      - frontend
      - backend
    environment:
      - PMA_ARBITRARY=1

  vpn_connector:
    container_name: twingate-connector
    image: twingate/connector:latest
    restart: unless-stopped
    pull_policy: always
    environment:
      - TWINGATE_NETWORK=${TWINGATE_NETWORK}
      - TWINGATE_ACCESS_TOKEN=${TWINGATE_ACCESS_TOKEN}
      - TWINGATE_REFRESH_TOKEN=${TWINGATE_REFRESH_TOKEN}
      - TWINGATE_LOG_ANALYTICS=v2
      - TWINGATE_LOG_LEVEL=3
    networks:
      - backend
    sysctls:
      net.ipv4.ping_group_range: "0 2147483647"

volumes:
  db_data:

networks:
  frontend:
    name: gled_frontend_network
    driver: bridge
  backend:
    driver: bridge
    name: gled_vpn_bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.69.0/24
    driver_opts:
      com.docker.network.bridge.name: gled_vpn_bridge
